substitutions:
  name: gaggiuino
packages:
  athom.mini-switch: github://gwylanscheeren/Home-Automation/blob/master/esphome/packages/athom-mini-switch.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: v9qa2/ZN/EfHEwXg2GRt5wNg0SDh+QJvBrggLrtcCXA=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
