substitutions:
  name: athom-mini-switch-cbd299
packages:
  athom.mini-switch: github://athom-tech/athom-configs/athom-mini-switch.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: 2ksMS12YRsiYzIEtNzaxG0WPVwBfVwgNX4pcT9TXY20=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
