substitutions:
  name: athom-sw04-d3f04e
packages:
  athom.sw04: github://athom-tech/athom-configs/athom-sw04.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: Sm02T//1yacuBF23llDfXkeBM1/qjH8CmTUXIyUXefM=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
