substitutions:
  name: athom-mini-switch-cbd299
packages:
  athom.mini-switch: github://gwylanscheeren/Home-Automation/esphome/packages/athom-mini-switch.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: MvInK71NgFC3fPXCkkyChLH6LwK9oTA3QO5HNkaWJPk=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
