substitutions:
  name: athom-sw02-d9debd
packages:
  athom.sw02: github://athom-tech/athom-configs/athom-sw02.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: UkN7p9oswh+GVnlje7Fx/aybz4QhiQQ4olkik9wIm2I=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
