static_ip_testquin: 192.168.1.30
static_ip_boochcontrol: 192.168.1.5
static_ip_bathroom_pk: 192.168.1.33
static_ip_kitchen: 192.168.1.4
static_gateway: 192.168.2.254
static_subnet: 255.255.255.0

mqtt_broker: 192.168.2.8
mqtt_user: gwylan
mqtt_pass: XmhfesM7
ota_pass: XmhfesM7

# Your Wi-Fi SSID and password
wifi_ssid: "Penny get your own wifi!"
wifi_password: "PennyisafreeloadeR!"
