esphomeyaml:
  name: 'testquin'
  platform: ESP32
  board: mhetesp32devkit

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

  # Optional manual IP
  manual_ip:
    static_ip: !secret static_ip_testquin
    gateway: !secret static_gateway
    subnet: !secret static_subnet

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_pass

# Enable logging
logger:
  level: DEBUG

ota:
  password: !secret ota_pass

dallas:
  - pin: GPIO18

switch:
  - platform: gpio
    name: "testQuin_onboard_light"
    pin: 2

output:
  - platform: ledc
    pin: 16
    frequency: 40000Hz
    bit_depth: 10
    id: LED_gpio_16

  - platform: ledc
    pin: 17
    frequency: 40000Hz
    bit_depth: 10
    id: LED_gpio_17

  - platform: ledc
    pin: 5
    frequency: 40000Hz
    bit_depth: 10
    id: LED_gpio_5

  - platform: ledc
    pin: 19
    frequency: 40000Hz
    bit_depth: 10
    id: LED_gpio_19

light:
  - platform: rgbw
    name: "testquin_RGBW_strip"
    red: LED_gpio_16
    green: LED_gpio_17
    blue: LED_gpio_5
    white: LED_gpio_19
    default_transition_length: 2s
    effects:
      - random:          
          name: "My Slow Random Effect"
          transition_length: 20s
          update_interval: 20s
      - random:
          name: "My Fast Random Effect"
          transition_length: 4s
          update_interval: 5s
      - random:
          name: "My Insane Random Effect"
          transition_length: 1s
          update_interval: 1s
      - random:          
          name: "Totally loco"
          transition_length: 300ms
          update_interval: 250ms

sensor:
  - platform: dallas
    index: 0
    name: "testquin_tempsensor"
